add-controllers
RomanDobrovolskiy/java-shareit pull request #1
Opened 2022-08-03 05:21 UTC by RomanDobrovolskiy

2022-08-03 20:00 UTC, Fleaman777 requested changes

2022-08-03 20:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final UserController userController;
вместо юзер котроллера лучше использовть юзер сервис, так будет более правильная структура, 

контроллер пользуется различными сервисами, что бы представлять данные, 

а публичные методы контроллера нужны для того, что бы маппить эндпоинты

2022-08-03 20:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        }
эти if'ы лучше вынести в отдельный валидационный метод

2022-08-03 20:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +            throw new NullPointerException("Не указано название предмета");
обычно NPE вылетает в немного других привычных нам местах, при знакомых нам обстоятельствах. 
здесь хорошо было бы использовать какой-нибудь свой кастомный эксепшен,

2022-08-03 20:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto create(@RequestBody ItemDto itemDto, @RequestHeader("X-Sharer-User-Id") String userId) {
userId можно сразу попробовать сделать типом int

2022-08-03 20:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                              @RequestHeader("X-Sharer-User-Id") int userId,
отлично, здесь юзер айди сразу int

2022-08-03 20:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return null;
можно добавить лог, почему метод возвращает null

2022-08-03 20:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private Map<Integer, Item> items = new HashMap<>();
хранение айтемом и работу со стореджом лучше перенести в отдельную директорию dao со своим интерфейсом, 
что бы поэтапно было проще разрабатывать приложение: 
сейчас у нас айтемы хранятся в хэшмапе, доступ к которой осуществляется через специальные методы, которые должны быть определены в интерфейсе, 
затем айтемы будут храниться в бд, доступ к которым будет через те же методы что и к хэшмап, только с другой реализацией

2022-08-03 20:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        items.get(itemId)
например, когда будет отдельный класс для работы со стореджем, тут будет метод ......getById(id)

2022-08-03 20:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        items.get(itemId)
можно items.get(itemId) вынести в локальную переменную, что бы постоянно не делать items.get(itemId)

2022-08-03 20:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            }
хороший кандидат на то, что бы эту логику сделать через стрим

2022-08-03 20:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    }
когда в конструкторе больше чем 4 поля, лучше использовать билдер, 
так код будет чуть лучше восприниматься

2022-08-03 20:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    }
аналагично с комментов в ItemDto

2022-08-03 20:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    private Map<Integer, User> users = new HashMap<>();
здесь аналагично с ItemService, 
эту хэшмап и работу с ней, лучше вынести в отдельный для этого пекедж

2022-08-03 20:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +            throw new NullPointerException("Пользователь с id " + userId + " не найден");
здесь можно будет использовать наш кастомный NPE

2022-08-03 20:00 UTC, Fleaman777 commented on .github/workflows/api-tests.yml
> +name: Films API Tests
а почему не ShareIt, а Film ?

2022-08-06 09:35 UTC, RomanDobrovolskiy commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            }
если возможно, хотел бы оставить в таком виде)

2022-08-06 10:16 UTC, closed without merging

2022-08-07 16:01 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/dao/ItemRepository.java
> +
можно было бы добавить методы getById, getAll, create, delete, update 
а в InMemoryItemRepository имплементировать эти методы, и соответственно в сервисе их использовать

2022-08-07 16:01 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/dao/UserRepository.java
> +}
здесь аналагично с ItemRepository