add-bookings
RomanDobrovolskiy/java-shareit pull request #6
Opened 2022-08-23 08:33 UTC by RomanDobrovolskiy

2022-08-24 07:50 UTC, Fleaman777 requested changes

2022-08-24 07:50 UTC, Fleaman777 commented on db/shareit.trace.db
> +	at java.base/java.lang.Thread.run(Thread.java:829)
временные файлы лучше не пушить, смысла от них не много, только места занимать будут,

2022-08-24 07:50 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/dto/OutputBookingDto.java
> +public class OutputBookingDto {
более привычное название будет 
BookingRequestDto и BookingResponseDto

2022-08-24 07:50 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        LocalDateTime now = LocalDateTime.now();
здорово что текущую даты вынес в локальную переменную

2022-08-24 07:50 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                           @RequestHeader(value = "X-Sharer-User-Id", required = false) Long userId) {
здесь X-Sharer-User-Id тоже можно вынести в константу

2022-08-24 07:50 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        }
логику в этом foreach можно было бы перенести в метод в стриме peek 

тогда можно будет сразу вернуть результат стрима, без создания локальной переменной items

2022-08-24 07:50 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/UserDto.java
> +    String email;
поля должны быть private

2022-08-24 07:50 UTC, Fleaman777 commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS users, items, bookings, comments;
а для чего нужна очистка таблиц ?
для гитхаб тестов ?

2022-08-24 07:50 UTC, Fleaman777 commented on src/main/resources/schema.sql
> +    start_time TIMESTAMP                               NOT NULL,
можно было бы добавить значение по дефолту

2022-08-29 06:15 UTC, RomanDobrovolskiy commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS users, items, bookings, comments;
убрать забыл, тестировал)

2022-08-29 06:24 UTC, RomanDobrovolskiy commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS users, items, bookings, comments;
протестировал, id не сбрасываются без очистки

2022-08-29 08:01 UTC, RomanDobrovolskiy commented
понять не могу, почему на гите фейлит тесты, постман все проходит

2022-08-31 05:26 UTC, merged